#!/bin/bash

RETRIES=5
COUNT=0

cd

if [ -z $1 ]
then
        echo "File not specified! Usage: flash_flexi [file]"
        exit
fi

~/bootloader_flexi

while [ $COUNT -lt $RETRIES ]
do
	stm32flash /dev/ttyAMA0 -b 115200 -w $1
	RETVAL=$?
	if [ $RETVAL -eq 0 ]
	then
		echo "Success!"
		break
	fi
	
	((COUNT++))
	
	if [ $COUNT -lt $RETRIES ]
	then
		echo "Error flashing, retrying..."
		sleep 2
	else
		echo "Error! Flashing unsuccessful!"
		exit
	fi
done

~/reset_flexi
