#!/bin/bash

echo "Entering bootloader..."

#Serial port needs to be open when toggling GPIOs to get board to enter serial bootloader
stty -F /dev/ttyAMA0 115200
read -t 5 < /dev/ttyAMA0 &

raspi-gpio set 18 op dh
sleep 1
raspi-gpio set 17 op dl
sleep 1
raspi-gpio set 17 ip
sleep 1
raspi-gpio set 18 ip
sleep 2
